(define (problem testdomain_task)
(:domain testdomain)
(:objects
    person1 person2 person3 - person
    robot1 robot2 - robot
    wp_dock1 wp_dock2 wp1 wp2 wp3 wp4 wp5 - waypoint
)
(:init
    (allowed_goto_waypoint robot1)
    (allowed_goto_waypoint robot2)
    (at 0 (arrived person1))
    (at 0 (arrived person2))
    (at 40 (arrived person3))
    (destination_waypoint wp2)
    (destination_waypoint wp3)
    (destination_waypoint wp4)
    (dock_at wp_dock1)
    (dock_at wp_dock2)
    (docked robot1)
    (docked robot2)
    (at 0 (free_person person1))
    (at 0 (free_person person2))
    (at 40 (free_person person3))
    (general_waypoint wp_dock1)
    (general_waypoint wp_dock2)
    (general_waypoint wp1)
    (general_waypoint wp2)
    (general_waypoint wp3)
    (general_waypoint wp4)
    (general_waypoint wp5)
    (greeting_waypoint wp1)
    (at 0 (person_at person1 wp1))
    (at 0 (person_at person2 wp1))
    (at 40 (person_at person3 wp1))
    (robot_at robot1 wp_dock1)
    (robot_at robot2 wp_dock2)
    (= (battery robot1) 100)
    (= (battery robot2) 100)
    (= (charging-rate robot1) 1.05)
    (= (charging-rate robot2) 1.05)

    (= (staying-rate person1) 1.2)
    (= (staying-rate person2) 1.8)
    (= (staying-rate person3) 1.2)
    (= (total_stay person1) 1)
    (= (total_stay person2) 1)
    (= (total_stay person3) 1)


    (= (consumption-rate robot1) 0.9)
    (= (consumption-rate robot2) 0.9)
    (= (velocity robot1) 3)
    (= (velocity robot2) 2)

    (= (distance_x_y wp1 wp2) 2)
    (= (distance_x_y wp1 wp3) 4)
    (= (distance_x_y wp1 wp4) 6)
    (= (distance_x_y wp1 wp5) 8)
    (= (distance_x_y wp1 wp_dock1) 4.924429)
    (= (distance_x_y wp1 wp_dock2) 4.031129)
    (= (distance_x_y wp2 wp1) 2)
    (= (distance_x_y wp2 wp3) 2)
    (= (distance_x_y wp2 wp4) 4)
    (= (distance_x_y wp2 wp5) 6)
    (= (distance_x_y wp2 wp_dock1) 3.201562)
    (= (distance_x_y wp2 wp_dock2) 2.5)
    (= (distance_x_y wp3 wp1) 4)
    (= (distance_x_y wp3 wp2) 2)
    (= (distance_x_y wp3 wp4) 2)
    (= (distance_x_y wp3 wp5) 4)
    (= (distance_x_y wp3 wp_dock1) 2.061553)
    (= (distance_x_y wp3 wp_dock2) 2.061553)
    (= (distance_x_y wp4 wp1) 6)
    (= (distance_x_y wp4 wp2) 4)
    (= (distance_x_y wp4 wp3) 2)
    (= (distance_x_y wp4 wp5) 2)
    (= (distance_x_y wp4 wp_dock1) 2.5)
    (= (distance_x_y wp4 wp_dock2) 3.201562)
    (= (distance_x_y wp5 wp1) 8)
    (= (distance_x_y wp5 wp2) 6)
    (= (distance_x_y wp5 wp3) 4)
    (= (distance_x_y wp5 wp4) 2)
    (= (distance_x_y wp5 wp_dock1) 4.031129)
    (= (distance_x_y wp5 wp_dock2) 4.924429)
    (= (distance_x_y wp_dock1 wp1) 4.924429)
    (= (distance_x_y wp_dock1 wp2) 3.201562)
    (= (distance_x_y wp_dock1 wp3) 2.061553)
    (= (distance_x_y wp_dock1 wp4) 2.5)
    (= (distance_x_y wp_dock1 wp5) 4.031129)
    (= (distance_x_y wp_dock1 wp_dock2) 1)
    (= (distance_x_y wp_dock2 wp1) 4.031129)
    (= (distance_x_y wp_dock2 wp2) 2.5)
    (= (distance_x_y wp_dock2 wp3) 2.061553)
    (= (distance_x_y wp_dock2 wp4) 3.201562)
    (= (distance_x_y wp_dock2 wp5) 4.924429)
    (= (distance_x_y wp_dock2 wp_dock1) 1)



)
(:goal (and
    (person_guided person1)
    (person_guided person2)
    (person_guided person3)
    (person_greeted person1)
    (person_greeted person2)
    (person_greeted person3)
    (person_at person1 wp2)
    (person_at person2 wp3)
    (person_at person3 wp4)
    (docked robot1)
    (docked robot2)
))

(:metric minimize ( + ( total_stay person3) (+ (total_stay person1) (total_stay person2)))) 
)
